spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: 'leonardo.oliveira.lo451@gmail.com'
    password: 'qtjy nwlw bvol qqey'
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
  thymeleaf:
    enabled: true

envio:
  email:
    remetente: 'leonardo.oliveira.lo451@gmail.com'
    nomeRemetente: 'Leonardo'

server:
  port: 8082